@echo off                     
RaspPicoImg background.bmp     background.cpp     BackgroundImg
RaspPicoImg blacksreds.bmp     blacksreds.cpp     BlacksRedsImg
RaspPicoImg cards.bmp          cards.cpp          CardsImg
RaspPicoImg castle.bmp         castle.cpp         CastleImg
RaspPicoImg castle_shadow.bmp  castle_shadow.cpp  CastleShadow
RaspPicoImg cloud.bmp          cloud.cpp          CloudImg
RaspPicoImg cursor.bmp         cursor.cpp         CursorImg
RaspPicoImg fence.bmp          fence.cpp          FenceImg
RaspPicoImg fence_shadow.bmp   fence_shadow.cpp   FenceShadowImg
RaspPicoImg flags.bmp          flags.cpp          FlagsImg
RaspPicoImg grass.bmp          grass.cpp          GrassImg
RaspPicoImg open.bmp           open.cpp           OpenImg
RaspPicoImg open_sel.bmp       open_sel.cpp       OpenSelImg
RaspPicoImg open_sel2.bmp      open_sel2.cpp      OpenSel2Img
RaspPicoImg select.bmp         select.cpp         SelectImg
RaspPicoImg state.bmp          state.cpp          StateImg
RaspPicoImg title.bmp          title.cpp          TitleImg
RaspPicoImg title2.bmp         title2.cpp         Title2Img
RaspPicoImg trumpet.bmp        trumpet.cpp        TrumpetImg
RaspPicoImg win.bmp            win.cpp            WinImg
