
// ****************************************************************************
//
//                                 Game levels
//
// ****************************************************************************

#include "include.h"

// level scenes
const u8 Levels[(LEVNUM+1)*MAPSIZE] = {
// 0
	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
	CRY,CRY,CRY,CRY,CRY,TRE,TRE,TRE,  0,  0,  0,CRO,  0,  0,CAK,APL,  0,  0,  0,APL,
	  0,  0,CRY,  0,  0,TRE,  0,  0,TRE,  0,CRO,  0,CRO,  0,CAK,APL,APL,  0,  0,APL,
	  0,  0,CRY,  0,  0,TRE,  0,  0,TRE,CRO,  0,  0,  0,CRO,CAK,APL,  0,APL,  0,APL,
	  0,  0,CRY,  0,  0,TRE,TRE,TRE,  0,CRO,  0,  0,  0,CRO,CAK,APL,  0,APL,  0,APL,
	  0,  0,CRY,  0,  0,TRE,  0,  0,TRE,CRO,CRO,CRO,CRO,CRO,CAK,APL,  0,APL,  0,APL,
	  0,  0,CRY,  0,  0,TRE,  0,  0,TRE,CRO,  0,  0,  0,CRO,CAK,APL,  0,  0,APL,APL,
	  0,  0,CRY,  0,  0,TRE,  0,  0,TRE,CRO,  0,  0,  0,CRO,CAK,APL,  0,  0,  0,APL,
	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
	LOC,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
	LEM,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 1
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,LOC,  0,  0,  0,  0,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,CRY,CRY,CRY,CRY,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,GAT,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 2
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,CRY,  0,CRY,  0,CRY,  0,CRY,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,CRO,  0,CRO,  0,CRO,  0,CRO,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,CRO,CRO,CRO,CRO,CRO,CRO,CRO,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,CRO,CRO,CRO,CRO,CRO,CRO,CRO,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,CRO,CRO,CRO,CRO,CRO,CRO,CRO,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,WAL,WAL,WAL,WAL,WAL,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,LOC,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 3
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,CRY,  0,  0,  0,  0,  0,WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,CRY,CRY,CRY,  0,  0,  0,  0,WAL,  0,  0,  0,TRE,  0,TRE,  0,  0,  0,WAL,
	WAL,  0,CRY,CRO,CRY,  0,  0,  0,  0,WAL,  0,  0,TRE,  0,LEM,  0,TRE,  0,  0,WAL,
	WAL,  0,CRY,CRY,CRY,  0,  0,  0,  0,WAL,  0,  0,  0,TRE,  0,TRE,  0,  0,  0,WAL,
	WAL,  0,  0,CRY,  0,  0,  0,  0,  0,GAT,  0,  0,TRE,  0,LEM,  0,TRE,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,  0,  0,  0,TRE,  0,TRE,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,LOC,  0,  0,  0,  0,  0,WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 4
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,CRY,  0,CRY,  0,CRY,  0,CRY,  0,CRY,  0,CRY,  0,CRY,  0,CRY,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,LOC,  0,  0,  0,  0,  0,  0,  0,APL,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,APL,APL,APL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,APL,APL,LEM,APL,APL,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,WAL,  0,  0,APL,APL,TRE,WAL,TRE,APL,APL,  0,  0,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,WAL,  0,APL,APL,TRE,APL,WAL,APL,TRE,APL,APL,  0,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,WAL,APL,APL,TRE,APL,APL,APL,APL,APL,TRE,APL,APL,WAL,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 5
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,TRE,TRE,TRE,TRE,TRE,TRE,TRE,LEM,TRE,TRE,TRE,TRE,TRE,TRE,TRE,TRE,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,COW,  0,COW,  0,COW,  0,WAL,  0,  0,COW,  0,COW,  0,COW,  0,  0,WAL,
	WAL,LOC,  0,  0,COW,  0,COW,  0,  0,WAL,  0,  0,  0,COW,  0,COW,  0,  0,  0,WAL,
	WAL,  0,  0,COW,  0,COW,  0,COW,  0,WAL,  0,  0,COW,  0,COW,  0,COW,  0,  0,WAL,
	WAL,  0,  0,  0,COW,  0,COW,  0,  0,WAL,  0,  0,  0,COW,  0,COW,  0,  0,  0,WAL,
	GAT,  0,  0,COW,  0,COW,  0,COW,  0,WAL,  0,  0,COW,  0,COW,  0,COW,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,CRO,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 6
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,LEM,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,CHE,CHE,CHE,  0,  0,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,CHE,CHE,CHE,CHE,CHE,  0,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,CHE,CHE,CHE,CHE,CHE,  0,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,LOC,  0,  0,  0,  0,  0,CHE,CHE,CRO,CHE,CHE,  0,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,CHE,CHE,CHE,CHE,CHE,  0,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,CHE,CHE,CHE,CHE,CHE,  0,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,CHE,CHE,CHE,  0,  0,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,CRY,  0,  0,  0,WAL,
	GAT,  0,  0,TRE,TRE,TRE,TRE,TRE,TRE,TRE,TRE,TRE,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 7
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,CRY,  0,  0,  0,TRE,LEM,TRE,  0,  0,  0,COW,  0,COW,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,  0,  0,TRE,  0,POL,  0,TRE,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,LOC,  0,  0,CRY,  0,  0,TRE,POL,  0,POL,TRE,  0,  0,  0,COW,  0,COW,  0,WAL,
	WAL,  0,  0,  0,WAL,  0,  0,TRE,  0,POL,  0,TRE,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,CRY,  0,  0,TRE,POL,  0,POL,TRE,  0,  0,COW,  0,COW,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,  0,  0,TRE,  0,WAL,  0,TRE,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,CRY,  0,  0,  0,TRE,WAL,TRE,  0,  0,  0,  0,COW,  0,COW,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 8
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,CRY,  0,WAL,WAL,WAL,WAL,  0,WAL,WAL,WAL,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,  0,  0,CRY,  0,WAL,  0,  0,  0,  0,  0,  0,  0,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,  0,  0,CRY,  0,WAL,  0,  0,TRE,  0,TRE,  0,  0,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,LOC,  0,CRY,  0,WAL,  0,APL,  0,GIR,  0,APL,  0,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,  0,  0,CRY,  0,WAL,  0,  0,TRE,  0,TRE,  0,  0,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,  0,  0,CRY,  0,WAL,  0,  0,  0,POL,  0,  0,  0,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,  0,  0,CRY,  0,WAL,  0,TRE,  0,  0,  0,TRE,  0,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,  0,  0,CRY,  0,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,GAT,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 9
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,APL,APL,APL,APL,APL,APL,APL,APL,APL,APL,APL,APL,APL,APL,APL,APL,APL,APL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,TRE,TRE,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,WAL,WAL,WAL,WAL,WAL,WAL,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,WAL,  0,  0,  0,  0,WAL,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,CRY,CRY,  0,  0,WAL,  0,ICE,ICE,  0,WAL,  0,  0,CRY,CRY,  0,  0,WAL,
	WAL,  0,CRY,CRY,CRY,CRY,  0,WAL,  0,ICE,ICE,  0,WAL,  0,CRY,CRY,CRY,CRY,  0,WAL,
	WAL,  0,CRY,CRY,CRY,CRY,  0,WAL,  0,ICE,ICE,  0,WAL,  0,CRY,CRY,CRY,CRY,  0,WAL,
	WAL,  0,  0,CRY,CRY,  0,  0,WAL,  0,ICE,ICE,  0,WAL,  0,  0,CRY,CRY,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,WAL,WAL,  0,  0,WAL,WAL,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,LOC,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 10
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,TRE,  0,  0,  0,ICE,  0,ICE,  0,ICE,  0,  0,  0,TRE,  0,  0,  0,WAL,
	WAL,  0,  0,TRE,  0,  0,  0,  0,ICE,  0,ICE,  0,  0,  0,  0,TRE,  0,  0,  0,WAL,
	WAL,  0,  0,TRE,  0,WAL,  0,  0,  0,CRY,  0,  0,  0,WAL,  0,TRE,  0,  0,  0,WAL,
	WAL,  0,  0,TRE,  0,WAL,  0,  0,  0,CRO,  0,  0,  0,WAL,  0,TRE,  0,  0,  0,WAL,
	WAL,LOC,  0,POL,  0,WAL,  0,  0,WAL,GAT,WAL,  0,  0,WAL,  0,GIR,  0,  0,  0,WAL,
	WAL,  0,  0,TRE,  0,WAL,COW,  0,WAL,CAK,WAL,  0,COW,WAL,  0,TRE,  0,  0,  0,WAL,
	WAL,  0,  0,TRE,  0,WAL,  0,  0,WAL,CRY,WAL,  0,  0,WAL,  0,TRE,  0,  0,  0,WAL,
	WAL,  0,  0,TRE,  0,WAL,  0,  0,WAL,CRY,WAL,  0,  0,WAL,  0,TRE,  0,  0,  0,WAL,
	WAL,  0,  0,TRE,  0,WAL,  0,  0,WAL,CRY,WAL,  0,  0,WAL,  0,TRE,  0,  0,  0,WAL,
	WAL,  0,  0,LEM,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,LEM,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 11
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,POL,  0,WAL,WAL,  0,POL,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,WAL,  0,COM,COM,  0,WAL,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,COM,COM,  0,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,COM,COM,  0,  0,WAL,
	WAL,  0,  0,COM,COM,  0,WAL,  0,  0,CRO,CRO,  0,  0,WAL,  0,COM,COM,  0,  0,WAL,
	WAL,LOC,  0,COM,  0,  0,  0,GAT,  0,  0,  0,  0,CRO,  0,  0,  0,COM,  0,  0,WAL,
	WAL,  0,  0,COM,  0,WAL,TRE,WAL,COM,  0,  0,COM,WAL,TRE,WAL,  0,COM,  0,  0,WAL,
	WAL,  0,  0,COM,  0,WAL,TRE,WAL,  0,COM,COM,  0,WAL,TRE,WAL,  0,COM,  0,  0,WAL,
	WAL,  0,COM,COM,  0,WAL,TRE,WAL,  0,COM,COM,  0,WAL,TRE,WAL,  0,COM,COM,  0,WAL,
	WAL,  0,COM,COM,  0,WAL,TRE,WAL,COM,COM,COM,COM,WAL,TRE,WAL,  0,COM,COM,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,WAL,  0,  0,  0,  0,WAL,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 12
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,COW,COW,COW,COW,COW,COW,COW,COW,COW,COW,COW,COW,COW,COW,COW,COW,  0,WAL,
	WAL,  0,COW,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,COW,  0,WAL,
	WAL,  0,COW,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,COW,  0,WAL,
	WAL,LOC,COW,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,COW,  0,WAL,
	WAL,  0,COW,  0,CAK,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,CAK,  0,COW,  0,WAL,
	WAL,  0,COW,  0,WAL,WAL,WAL,WAL,WAL,LEM,WAL,WAL,WAL,WAL,WAL,WAL,  0,COW,  0,WAL,
	WAL,  0,COW,  0,WAL,CAR,CAR,CAR,CAR,  0,CAR,CAR,CAR,CAR,CAR,WAL,  0,COW,  0,WAL,
	WAL,  0,COW,  0,WAL,CAR,CAR,CAR,CAR,  0,CAR,CAR,CAR,CAR,CAR,WAL,  0,COW,  0,WAL,
	WAL,  0,  0,  0,WAL,CAR,CAR,CAR,CAR,  0,CAR,CAR,CAR,CAR,CAR,WAL,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 13
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,ICE,ICE,WAL,WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,APL,APL,WAL,
	WAL,WAL,ICE,ICE,ICE,WAL,  0,  0,  0,BAL,  0,  0,  0,  0,  0,  0,  0,APL,APL,WAL,
	WAL,WAL,ICE,LEM,ICE,WAL,  0,  0,BAL,  0,BAL,  0,  0,  0,  0,  0,  0,WAL,WAL,WAL,
	WAL,WAL,WAL,ICE,ICE,WAL,  0,  0,  0,BAL,  0,GIR,TRE,CRO,  0,  0,  0,  0,  0,WAL,
	WAL,LOC,  0,  0,  0,  0,  0,  0,  0,  0,COW,TRE,WAL,WAL,  0,CRY,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,GIR,TRE,WAL,WAL,WAL,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,COW,TRE,WAL,WAL,WAL,CRY,  0,CRY,  0,  0,  0,  0,CAK,WAL,
	WAL,  0,  0,  0,GIR,TRE,WAL,WAL,WAL,CRY,  0,  0,  0,  0,  0,  0,  0,WAL,WAL,WAL,
	WAL,  0,  0,TRE,WAL,WAL,WAL,CRY,  0,  0,CRY,  0,CRY,  0,CRY,  0,  0,APL,APL,WAL,
	WAL,  0,COW,WAL,WAL,  0,  0,  0,CRY,  0,  0,  0,CAR,CAR,CAR,  0,  0,APL,APL,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 14
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,CLK,CLK,CLK,  0,CLK,  0,CLK,  0,  0,CLK,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,CLK,  0,  0,CLK,  0,CLK,  0,CLK,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,CLK,  0,  0,CLK,  0,CLK,CLK,  0,  0,  0,CLK,CLK,CLK,  0,  0,  0,  0,WAL,
	WAL,  0,CLK,  0,  0,CLK,  0,CLK,  0,CLK,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	GAT,LOC,CLK,  0,  0,CLK,  0,CLK,  0,  0,CLK,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,CLK,CLK,CLK,  0,  0,CLK,  0,  0,CLK,  0,CLK,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,CLK,  0,  0,CLK,  0,CLK,  0,CLK,CLK,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,CLK,  0,  0,CLK,CLK,CLK,  0,CLK,  0,CLK,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,CLK,  0,  0,CLK,  0,CLK,  0,CLK,  0,CLK,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 15
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,CRY,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,WAL,WAL,WAL,CRO,WAL,WAL,WAL,WAL,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,ELE,TRE,ELE,  0,  0,  0,  0,POL,TRE,POL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,TRE,ELE,TRE,  0,WAL,CHE,  0,TRE,POL,TRE,WAL,  0,  0,  0,WAL,
	WAL,LOC,  0,  0,GAT,WAL,WAL,WAL,COM,APL,WAL,CAR,WAL,WAL,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,WAL,WAL,ICE,APL,WAL,ICE,WAL,WAL,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,TRE,GIR,TRE,CAK,WAL,ICE,CAK,TRE,COW,TRE,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,GIR,TRE,GIR,CAK,CAK,CAK,CAK,COW,TRE,COW,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 16
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,WAL,GLA,GLA,GLA,GLA,GLA,GLA,GLA,GLA,GLA,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,WAL,GLA,GLA,GLA,GLA,GLA,GLA,GLA,WAL,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,WAL,GLA,GLA,GLA,GLA,GLA,WAL,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,WAL,GLA,GLA,GLA,WAL,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,LOC,  0,  0,  0,  0,  0,WAL,GAT,WAL,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,CRY,WAL,CRY,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,CRY,WAL,CRY,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,WAL,WAL,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,CRO,CRO,CRO,CRO,CRO,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 17
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,CRY,CRO,CRY,CRO,CAR,CAR,CAR,CAR,CAR,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,CRO,CRY,CRO,CRY,WAL,WAL,WAL,WAL,MON,WAL,WAL,WAL,WAL,WAL,  0,  0,  0,  0,WAL,
	WAL,CRY,CRO,WAL,CRO,WAL,MON,MON,MON,MON,WAL,MON,MON,MON,WAL,  0,  0,  0,  0,WAL,
	WAL,CRO,CRY,CRO,CRY,WAL,MON,WAL,WAL,WAL,WAL,MON,WAL,MON,WAL,  0,  0,  0,  0,WAL,
	WAL,CRY,CRO,CRY,CRO,WAL,MON,MON,MON,MON,MON,MON,WAL,MON,WAL,  0,  0,  0,  0,WAL,
	WAL,LOC,CRY,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,MON,MON,WAL,  0,  0,  0,  0,WAL,
	WAL,CRY,CRO,CRY,CRO,WAL,MON,MON,MON,MON,WAL,MON,MON,WAL,WAL,  0,  0,  0,  0,WAL,
	WAL,CRO,WAL,WAL,CRY,WAL,MON,WAL,WAL,MON,MON,MON,MON,MON,WAL,  0,  0,  0,  0,WAL,
	WAL,CRY,CRO,CRY,CRO,WAL,MON,MON,MON,WAL,WAL,WAL,MON,MON,WAL,  0,  0,  0,  0,WAL,
	WAL,CRO,CRY,CRO,CRY,WAL,MON,MON,MON,MON,MON,MON,MON,MON,WAL,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,

// 18
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,WAL,  0,  0,  0,  0,  0,  0,  0,GAT,  0,  0,  0,  0,  0,WAL,
	WAL,  0,CAK,  0,  0,WAL,AIR,  0,WAL,  0,WAL,  0,AIR,WAL,  0,  0,  0,ICE,  0,WAL,
	WAL,  0,CAK,  0,  0,WAL,  0,  0,WAL,  0,WAL,  0,  0,WAL,  0,  0,ICE,ICE,  0,WAL,
	WAL,  0,CAK,CAK,  0,WAL,WAL,WAL,  0,  0,  0,WAL,WAL,WAL,  0,ICE,ICE,ICE,  0,WAL,
	WAL,  0,CAK,CAK,  0,  0,CRY,  0,  0,GIR,  0,  0,CRY,  0,ICE,ICE,ICE,ICE,  0,WAL,
	WAL,LOC,CAK,CAK,  0,  0,CRY,  0,  0,ELE,  0,  0,CRY,  0,ICE,ICE,ICE,ICE,  0,WAL,
	WAL,  0,CAK,CAK,  0,WAL,WAL,WAL,  0,  0,  0,WAL,WAL,WAL,  0,ICE,ICE,ICE,  0,WAL,
	WAL,  0,CAK,  0,  0,WAL,  0,  0,WAL,  0,WAL,  0,  0,WAL,  0,  0,ICE,ICE,  0,WAL,
	WAL,  0,CAK,  0,  0,WAL,AIR,  0,WAL,  0,WAL,  0,AIR,WAL,  0,  0,  0,ICE,  0,WAL,
	WAL,  0,  0,  0,  0,WAL,  0,  0,  0,  0,  0,  0,  0,WAL,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 19
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,WAL,
	WAL,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,WAL,
	WAL,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,WAL,
	WAL,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,WAL,
	WAL,LOC,CRY,CRY,CRY,CRY,CRY,CRY,GAT,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,WAL,
	WAL,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,WAL,
	WAL,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,WAL,
	WAL,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,WAL,
	WAL,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,WAL,
	WAL,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 20
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,CRO,  0,  0,  0,  0,  0,ELE,ELE,ELE,ELE,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,WAL,WAL,  0,  0,  0,  0,WAL,WAL,WAL,WAL,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,CRY,  0,WAL,  0,  0,WAL,TRE,GIR,TRE,GIR,WAL,  0,  0,  0,WAL,
	WAL,LOC,  0,  0,  0,  0,  0,  0,WAL,WAL,TRE,GIR,TRE,GIR,TRE,GIR,WAL,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,WAL,  0,  0,TRE,GIR,TRE,GIR,TRE,GIR,TRE,WAL,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,WAL,  0,GIR,TRE,GIR,TRE,GIR,TRE,GIR,TRE,WAL,CRY,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,WAL,WAL,GIR,TRE,GIR,LEM,GIR,TRE,GIR,GAT,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,WAL,  0,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,  0,WAL,
	WAL,CHE,APL,CHE,APL,CHE,APL,WAL,WAL,  0,  0,  0,  0,  0,WAL,WAL,  0,APL,CHE,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 21
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,TRE,TRE,TRE,TRE,WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,TRE,TRE,LEM,TRE,WAL,
	WAL,  0,COM,  0,  0,  0,WAL,  0,  0,  0,  0,  0,  0,WAL,  0,  0,  0,COM,  0,WAL,
	WAL,CLK,  0,CAK,  0,  0,  0,WAL,  0,  0,  0,  0,WAL,  0,  0,  0,CAK,  0,CLK,WAL,
	WAL,WAL,WAL,WAL,ICE,  0,  0,  0,WAL,  0,  0,WAL,  0,  0,  0,ICE,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,WAL,ICE,  0,  0,  0,WAL,WAL,  0,  0,  0,ICE,WAL,  0,  0,  0,WAL,
	WAL,CRY,CRY,  0,  0,WAL,ICE,  0,  0,LOC,  0,  0,  0,ICE,WAL,  0,  0,CRY,CRY,WAL,
	WAL,CRY,WAL,CRY,  0,  0,WAL,ICE,  0,GLA,GLA,  0,ICE,WAL,  0,  0,CRY,WAL,CRY,WAL,
	WAL,  0,  0,WAL,CRY,  0,  0,WAL,  0,GLA,GLA,  0,WAL,  0,  0,CRY,WAL,  0,  0,WAL,
	WAL,  0,CRO,  0,WAL,CRY,  0,  0,WAL,GLA,GLA,WAL,  0,  0,CRY,WAL,  0,CRO,  0,WAL,
	WAL,  0,  0,  0,  0,WAL,CRY,  0,  0,GLA,GLA,  0,  0,CRY,WAL,  0,  0,  0,  0,GAT,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 22
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,LOC,TRE,TRE,TRE,TRE,TRE,TRE,  0,TRE,WAL,TRE,  0,TRE,TRE,TRE,TRE,TRE,TRE,WAL,
	WAL,  0,TRE,TRE,LEM,TRE,TRE,TRE,TRE,TRE,WAL,TRE,TRE,TRE,TRE,TRE,LEM,TRE,TRE,WAL,
	WAL,TRE,TRE,TRE,TRE,TRE,TRE,  0,TRE,  0,WAL,  0,TRE,  0,TRE,TRE,TRE,TRE,TRE,WAL,
	WAL,  0,TRE,TRE,TRE,TRE,  0,TRE,WAL,WAL,WAL,WAL,WAL,TRE,  0,TRE,  0,TRE,TRE,WAL,
	WAL,TRE,TRE,TRE,TRE,  0,WAL,  0,WAL,  0,  0,  0,WAL,  0,WAL,  0,TRE,TRE,TRE,WAL,
	WAL,  0,TRE,TRE,TRE,  0,WAL,  0,WAL,  0,POL,  0,WAL,  0,WAL,  0,TRE,TRE,TRE,WAL,
	WAL,  0,  0,TRE,  0,  0,WAL,  0,WAL,  0,  0,  0,WAL,  0,WAL,  0,  0,TRE,  0,WAL,
	WAL,  0,TRE,TRE,TRE,TRE,WAL,  0,WAL,WAL,  0,WAL,WAL,  0,WAL,TRE,TRE,TRE,TRE,WAL,
	WAL,TRE,TRE,TRE,TRE,WAL,WAL,  0,  0,  0,  0,  0,  0,  0,WAL,WAL,TRE,TRE,TRE,WAL,
	GAT,  0,TRE,  0,TRE,  0,WAL,TRE,TRE,TRE,GIR,TRE,TRE,TRE,WAL,  0,TRE,  0,TRE,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 23
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,GLA,GLA,GLA,GLA,  0,  0,GLA,GLA,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,GLA,WAL,WAL,WAL,WAL,GLA,  0,GLA,GLA,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,GLA,WAL,WAL,WAL,WAL,WAL,WAL,GLA,GLA,GLA,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,GLA,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GLA,GLA,  0,  0,  0,  0,  0,  0,WAL,
	WAL,LOC,GLA,WAL,WAL,BAL,BAL,BAL,WAL,WAL,WAL,WAL,GLA,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,GLA,WAL,WAL,BAL,AIR,BAL,ICE,ICE,ICE,WAL,GLA,  0,TRE,  0,TRE,  0,TRE,WAL,
	WAL,  0,GLA,WAL,WAL,BAL,BAL,BAL,ICE,LEM,ICE,WAL,GLA,TRE,TRE,TRE,TRE,TRE,TRE,WAL,
	WAL,  0,GLA,WAL,WAL,WAL,WAL,WAL,ICE,ICE,ICE,WAL,GLA,  0,TRE,  0,TRE,  0,TRE,WAL,
	WAL,  0,GLA,WAL,WAL,WAL,WAL,WAL,ICE,ICE,WAL,WAL,GLA,  0,TRE,  0,TRE,  0,TRE,WAL,
	WAL,  0,GLA,GLA,GLA,GLA,GLA,GLA,GLA,GLA,GLA,GLA,GLA,  0,TRE,  0,TRE,  0,TRE,GAT,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 24
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,CHE,  0,  0,WAL,  0,WAL,  0,  0,  0,WAL,  0,WAL,  0,  0,  0,CHE,  0,WAL,
	WAL,  0,CHE,  0,  0,WAL,  0,WAL,  0,  0,  0,WAL,  0,WAL,  0,  0,  0,CHE,  0,WAL,
	WAL,WAL,WAL,WAL,  0,WAL,  0,WAL,  0,POL,  0,WAL,  0,WAL,  0,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,CHE,  0,  0,WAL,  0,WAL,  0,GIR,  0,WAL,  0,WAL,  0,  0,  0,CHE,  0,WAL,
	WAL,  0,WAL,WAL,WAL,WAL,  0,WAL,  0,  0,  0,WAL,  0,WAL,WAL,WAL,WAL,WAL,  0,WAL,
	WAL,  0,CHE,  0,  0,  0,  0,WAL,  0,  0,  0,WAL,  0,  0,  0,  0,  0,CHE,  0,WAL,
	WAL,  0,WAL,WAL,WAL,WAL,  0,WAL,WAL,LOC,WAL,WAL,  0,WAL,WAL,WAL,WAL,WAL,  0,WAL,
	WAL,  0,CHE,  0,  0,WAL,  0,  0,APL,  0,APL,  0,  0,WAL,  0,  0,  0,CHE,  0,WAL,
	WAL,  0,  0,  0,  0,WAL,TRE,  0,  0,  0,  0,  0,TRE,WAL,  0,  0,  0,  0,  0,WAL,
	WAL,  0,CHE,  0,  0,WAL,APL,APL,APL,APL,APL,APL,APL,WAL,  0,  0,  0,CHE,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 25
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,LOC,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,WAL,
	WAL,  0,CRO,  0,CRO,  0,CRO,  0,CRO,  0,  0,CRO,  0,CRO,  0,CRO,  0,CRO,  0,WAL,
	WAL,WAL,CAK,CAK,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CRY,CAK,CAK,WAL,WAL,
	WAL,WAL,CAK,CAK,WAL,CAK,CAK,  0,CRO,  0,  0,CRO,  0,CAK,CAK,WAL,CAK,CAK,WAL,WAL,
	WAL,WAL,CAK,CAK,WAL,CAK,CAK,WAL,CAK,WAL,CAK,CAK,WAL,CAK,CAK,WAL,CAK,CAK,WAL,WAL,
	WAL,WAL,CAK,CAK,WAL,CAK,CAK,WAL,CAK,WAL,CAK,CAK,WAL,CAK,CAK,WAL,CAK,CAK,WAL,WAL,
	WAL,WAL,CAK,CAK,WAL,CAK,CAK,WAL,CAK,WAL,CAK,CAK,WAL,CAK,CAK,WAL,CAK,CAK,WAL,WAL,
	WAL,WAL,CAK,CAK,WAL,CAK,CAK,WAL,CAK,WAL,CAK,CAK,WAL,CAK,CAK,WAL,CAK,CAK,WAL,WAL,
	WAL,WAL,CAK,CAK,WAL,CAK,CAK,WAL,CAK,WAL,CAK,CAK,WAL,CAK,CAK,WAL,CAK,CAK,WAL,WAL,
	WAL,WAL,CAK,CAK,WAL,CAK,CAK,WAL,CAK,WAL,CAK,CAK,WAL,CAK,CAK,WAL,CAK,CAK,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 26
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,  0,  0,  0,  0,  0,  0,APL,  0,CHE,  0,WAL,WAL,WAL,WAL,
	WAL,WAL,GIR,ELE,GIR,WAL,  0,  0,  0,TRE,TRE,POL,GLA,APL,WAL,CHE,  0,WAL,WAL,WAL,
	WAL,WAL,ELE,GIR,ELE,  0,  0,  0,TRE,WAL,WAL,TRE,POL,GLA,APL,WAL,CHE,  0,WAL,WAL,
	WAL,WAL,GIR,ELE,GIR,  0,  0,TRE,WAL,  0,  0,WAL,TRE,POL,GLA,APL,WAL,CHE,  0,WAL,
	WAL,WAL,ELE,GIR,ELE,  0,TRE,WAL,  0,  0,  0,  0,WAL,TRE,POL,GLA,APL,WAL,  0,WAL,
	WAL,WAL,WAL,WAL,  0,TRE,WAL,  0,  0,  0,  0,  0,  0,WAL,TRE,POL,GLA,APL,  0,WAL,
	WAL,  0,  0,  0,TRE,WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,TRE,POL,GLA,APL,WAL,
	WAL,  0,  0,TRE,WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,TRE,POL,GLA,WAL,
	WAL,  0,TRE,WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,TRE,POL,WAL,
	WAL,TRE,LOC,WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,GAT,LEM,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 27
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,LOC,CRY,WAL,WAL,  0,CRY,  0,  0,WAL,  0,  0,CRY,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,  0,WAL,  0,WAL,CRY,  0,WAL,WAL,WAL,WAL,WAL,  0,WAL,  0,WAL,
	WAL,WAL,WAL,  0,WAL,  0,WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,CRY,  0,  0,WAL,  0,WAL,  0,WAL,WAL,  0,WAL,WAL,  0,CRY,  0,  0,WAL,
	WAL,  0,WAL,WAL,WAL,WAL,WAL,CRY,WAL,GAT,WAL,  0,CRY,  0,  0,WAL,  0,WAL,  0,WAL,
	WAL,  0,  0,  0,  0,WAL,  0,  0,WAL,CRO,  0,CRY,  0,WAL,CRY,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,  0,WAL,  0,WAL,WAL,  0,WAL,  0,CRY,WAL,  0,WAL,CRY,CRY,  0,WAL,
	WAL,  0,  0,  0,  0,WAL,  0,CRY,  0,WAL,  0,CRY,  0,WAL,  0,CRY,  0,  0,WAL,WAL,
	WAL,  0,WAL,WAL,  0,WAL,WAL,  0,  0,  0,WAL,  0,  0,WAL,CRY,  0,  0,WAL,  0,WAL,
	WAL,  0,CRY,  0,  0,  0,WAL,  0,  0,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 28
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,GAT,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,WAL,GIR,GIR,WAL,  0,  0,  0,  0,  0,  0,WAL,GIR,GIR,WAL,  0,  0,WAL,
	WAL,  0,WAL,GIR,GIR,GIR,GIR,WAL,  0,WAL,WAL,  0,WAL,GIR,GIR,GIR,GIR,WAL,  0,WAL,
	WAL,LOC,WAL,GIR,GIR,GIR,  0,  0,  0,ELE,ELE,  0,  0,  0,GIR,GIR,GIR,WAL,  0,WAL,
	WAL,  0,WAL,GIR,GIR,GIR,  0,GIR,ELE,ELE,ELE,ELE,WAL,  0,GIR,GIR,GIR,WAL,  0,WAL,
	WAL,  0,WAL,GIR,GIR,GIR,GIR,WAL,WAL,WAL,WAL,WAL,WAL,GIR,GIR,GIR,GIR,WAL,  0,WAL,
	WAL,  0,  0,WAL,GIR,GIR,WAL,  0,  0,  0,  0,  0,  0,WAL,GIR,GIR,WAL,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 29
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,WAL,  0,  0,  0,  0,WAL,  0,  0,  0,WAL,  0,  0,  0,  0,WAL,
	WAL,  0,  0,GIR,  0,WAL,  0,COW,  0,  0,WAL,  0,ELE,  0,WAL,  0,GIR,  0,  0,WAL,
	WAL,  0,  0,  0,  0,WAL,  0,  0,  0,  0,WAL,  0,  0,  0,WAL,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,  0,WAL,WAL,WAL,  0,WAL,WAL,LOC,WAL,  0,WAL,WAL,WAL,  0,WAL,WAL,WAL,
	WAL,TRE,  0,  0,  0,TRE,  0,  0,  0,  0,TRE,  0,  0,  0,TRE,  0,  0,  0,TRE,WAL,
	WAL,LEM,  0,  0,  0,TRE,  0,  0,  0,  0,TRE,  0,  0,  0,TRE,  0,  0,  0,LEM,WAL,
	WAL,WAL,WAL,  0,WAL,WAL,WAL,  0,WAL,WAL,GAT,WAL,  0,WAL,WAL,WAL,  0,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,WAL,  0,  0,  0,WAL,  0,  0,  0,  0,WAL,  0,  0,  0,  0,WAL,
	WAL,  0,  0,COW,  0,WAL,  0,ELE,  0,WAL,  0,  0,GIR,  0,WAL,  0,COW,  0,  0,WAL,
	WAL,  0,  0,  0,  0,WAL,  0,  0,  0,WAL,  0,  0,  0,  0,WAL,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 30
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,  0,WAL,
	WAL,  0,  0,WAL,CLK,CLK,CLK,CLK,CLK,WAL,WAL,CRY,CRY,CRY,CRY,CRY,WAL,  0,  0,WAL,
	WAL,  0,  0,WAL,POL,WAL,POL,POL,POL,WAL,WAL,CRO,CRO,CRO,WAL,CRO,WAL,  0,  0,WAL,
	WAL,  0,  0,WAL,ICE,WAL,WAL,ICE,ICE,WAL,WAL,APL,APL,WAL,WAL,APL,WAL,  0,  0,WAL,
	WAL,  0,  0,WAL,AIR,CAR,WAL,WAL,CAR,WAL,WAL,COM,WAL,WAL,COM,COM,WAL,  0,  0,WAL,
	WAL,  0,  0,WAL,CAK,CAK,CAK,WAL,CAK,WAL,WAL,COW,WAL,COW,COW,COW,WAL,  0,  0,WAL,
	WAL,  0,  0,WAL,BAL,BAL,BAL,BAL,BAL,WAL,WAL,GLA,GLA,GLA,GLA,GLA,WAL,  0,  0,WAL,
	WAL,  0,  0,WAL,WAL,WAL,WAL,TRE,TRE,WAL,WAL,TRE,TRE,WAL,WAL,WAL,WAL,  0,  0,WAL,
	WAL,LOC,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,GAT,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 31
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,CRY,  0,CRY,  0,CRY,  0,CRY,TRE,TRE,CRY,  0,CRY,  0,CRY,  0,CRY,  0,WAL,
	WAL,  0,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,WAL,
	WAL,  0,CRY,  0,CRY,  0,CRY,  0,CRY,TRE,TRE,CRY,  0,CRY,  0,CRY,  0,CRY,  0,WAL,
	WAL,  0,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,WAL,
	WAL,LOC,CRY,  0,CRY,  0,CRY,  0,CRY,TRE,TRE,CRY,  0,CRY,  0,CRY,  0,CRY,  0,WAL,
	WAL,  0,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,WAL,
	WAL,  0,CRY,  0,CRY,  0,CRY,  0,CRY,TRE,TRE,CRY,  0,CRY,  0,CRY,  0,CRY,  0,WAL,
	WAL,  0,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,WAL,
	WAL,  0,CRY,  0,CRY,  0,CRY,  0,CRY,TRE,TRE,CRY,  0,CRY,  0,CRY,  0,CRY,  0,WAL,
	WAL,  0,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 32
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,WAL,TRE,TRE,TRE,TRE,WAL,WAL,TRE,TRE,TRE,TRE,WAL,TRE,TRE,WAL,WAL,
	WAL,  0,  0,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,TRE,WAL,
	WAL,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,WAL,
	WAL,TRE,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,
	WAL,LOC,TRE,WAL,WAL,TRE,WAL,WAL,TRE,WAL,WAL,TRE,WAL,WAL,TRE,WAL,WAL,TRE,WAL,WAL,
	WAL,TRE,LEM,TRE,WAL,TRE,TRE,WAL,TRE,LEM,WAL,TRE,TRE,WAL,TRE,LEM,WAL,TRE,TRE,WAL,
	WAL,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,GAT,
	WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,WAL,
	WAL,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,
	WAL,WAL,WAL,TRE,TRE,TRE,TRE,WAL,WAL,TRE,TRE,TRE,TRE,WAL,WAL,TRE,TRE,TRE,TRE,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 33
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,ICE,WAL,WAL,WAL,ICE,  0,  0,CAK,CAK,  0,  0,CHE,CHE,CHE,CHE,  0,  0,WAL,
	WAL,  0,ICE,WAL,WAL,WAL,ICE,  0,CAK,WAL,WAL,CAK,  0,CHE,WAL,WAL,WAL,CHE,  0,WAL,
	WAL,  0,  0,ICE,WAL,ICE,  0,CAK,WAL,WAL,WAL,WAL,CAK,CHE,WAL,WAL,WAL,CHE,  0,WAL,
	WAL,  0,  0,ICE,WAL,ICE,  0,CAK,WAL,WAL,WAL,WAL,CAK,CHE,WAL,WAL,WAL,CHE,  0,WAL,
	WAL,LOC,  0,  0,ICE,  0,  0,CAK,WAL,WAL,WAL,WAL,CAK,CHE,WAL,WAL,WAL,CHE,  0,WAL,
	WAL,  0,  0,  0,ICE,  0,  0,CAK,WAL,WAL,WAL,WAL,CAK,CHE,CHE,CHE,CHE,  0,LEM,GAT,
	WAL,  0,  0,ICE,WAL,ICE,  0,CAK,WAL,WAL,WAL,WAL,CAK,CHE,WAL,CHE,  0,  0,  0,WAL,
	WAL,  0,  0,ICE,WAL,ICE,  0,CAK,WAL,WAL,WAL,WAL,CAK,CHE,WAL,WAL,CHE,  0,  0,WAL,
	WAL,  0,ICE,WAL,WAL,WAL,ICE,  0,CAK,WAL,WAL,CAK,  0,CHE,WAL,WAL,WAL,CHE,  0,WAL,
	WAL,  0,ICE,WAL,WAL,WAL,ICE,  0,  0,CAK,CAK,  0,  0,CHE,WAL,WAL,WAL,CHE,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 34
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,LOC,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,GLA,GLA,GLA,GLA,GLA,GLA,GLA,GLA,GLA,GLA,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,GLA,GLA,GLA,GLA,GLA,GLA,GLA,GLA,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,WAL,GLA,GLA,GLA,GLA,GLA,GLA,WAL,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,WAL,WAL,GLA,GLA,GLA,GLA,WAL,WAL,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,WAL,WAL,WAL,GLA,GLA,WAL,WAL,WAL,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,WAL,WAL,GLA,GLA,GLA,GLA,WAL,WAL,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,WAL,GLA,GLA,GLA,GLA,GLA,GLA,WAL,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,GLA,GLA,GLA,GLA,GLA,GLA,GLA,GLA,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,GLA,GLA,GLA,GLA,GLA,GLA,GLA,GLA,WAL,WAL,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 35
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,CRO,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,WAL,GAT,WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,WAL,COW,  0,GIR,WAL,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,WAL,COW,COW,  0,GIR,GIR,WAL,  0,  0,  0,  0,  0,  0,WAL,
	WAL,LOC,  0,  0,  0,WAL,COW,COW,COW,  0,GIR,GIR,GIR,WAL,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,WAL,COW,COW,COW,  0,GIR,GIR,GIR,WAL,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,WAL,COW,COW,  0,GIR,GIR,WAL,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,WAL,COW,  0,GIR,WAL,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,WAL,  0,WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,TRE,TRE,TRE,LEM,TRE,TRE,TRE,TRE,TRE,TRE,TRE,TRE,TRE,TRE,LEM,TRE,TRE,TRE,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 36
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,LOC,WAL,  0,  0,  0,WAL,  0,  0,  0,WAL,  0,  0,  0,WAL,  0,  0,  0,WAL,
	WAL,WAL,  0,WAL,  0,CRO,  0,WAL,  0,CRO,  0,WAL,  0,CRO,  0,WAL,  0,CRO,  0,WAL,
	WAL,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,
	WAL,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,
	WAL,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,
	WAL,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,
	WAL,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,
	WAL,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,  0,WAL,
	WAL,WAL,  0,CRO,  0,WAL,  0,CRO,  0,WAL,  0,CRO,  0,WAL,  0,CRO,  0,WAL,  0,WAL,
	WAL,WAL,  0,CRY,  0,WAL,  0,  0,  0,WAL,  0,  0,  0,WAL,  0,CRY,  0,WAL,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,

// 37
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,WAL,CHE,CHE,CHE,CHE,CHE,CHE,CHE,CHE,CHE,CHE,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,CHE,APL,APL,APL,CHE,CHE,APL,APL,APL,CHE,WAL,  0,  0,  0,WAL,
	WAL,  0,CRY,  0,WAL,CHE,APL,WAL,APL,CHE,CHE,APL,WAL,APL,CHE,WAL,  0,CRY,  0,WAL,
	WAL,  0,  0,  0,WAL,APL,APL,WAL,APL,APL,APL,APL,WAL,APL,APL,WAL,  0,  0,  0,WAL,
	WAL,LOC,CRY,  0,TRE,APL,WAL,WAL,WAL,APL,APL,WAL,WAL,WAL,APL,TRE,  0,CRY,  0,GAT,
	WAL,  0,  0,  0,WAL,APL,APL,WAL,APL,APL,APL,APL,WAL,APL,APL,WAL,  0,  0,  0,WAL,
	WAL,  0,CRY,  0,WAL,CHE,APL,WAL,APL,CHE,CHE,APL,WAL,APL,CHE,WAL,  0,CRY,  0,WAL,
	WAL,  0,  0,  0,WAL,CHE,APL,APL,APL,CHE,CHE,APL,APL,APL,CHE,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,CHE,CHE,CHE,CHE,CHE,CHE,CHE,CHE,CHE,CHE,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 38
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,LEM,  0,  0,LEM,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,AIR,  0,  0,  0,TRE,WAL,TRE,TRE,WAL,TRE,  0,  0,  0,AIR,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,TRE,WAL,  0,  0,  0,  0,WAL,TRE,  0,  0,  0,  0,  0,WAL,
	WAL,LOC,  0,  0,  0,TRE,WAL,  0,  0,WAL,TRE,  0,  0,WAL,TRE,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,TRE,WAL,  0,  0,  0,WAL,TRE,  0,  0,  0,WAL,TRE,  0,  0,  0,WAL,
	WAL,  0,  0,TRE,WAL,TRE,  0,TRE,  0,  0,WAL,  0,TRE,  0,TRE,WAL,TRE,  0,  0,WAL,
	WAL,  0,TRE,WAL,  0,  0,WAL,WAL,TRE,TRE,WAL,TRE,WAL,WAL,  0,  0,WAL,TRE,  0,WAL,
	WAL,  0,WAL,  0,  0,  0,WAL,  0,  0,WAL,  0,  0,  0,WAL,  0,  0,  0,WAL,TRE,GAT,
	WAL,WAL,  0,  0,  0,  0,WAL,  0,  0,WAL,  0,  0,  0,WAL,  0,  0,  0,  0,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 39
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,LOC,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,COM,COM,COM,COM,COM,COM,WAL,  0,  0,COM,COM,COM,COM,COM,COM,COM,WAL,  0,WAL,
	WAL,  0,COM,COM,WAL,  0,COM,COM,WAL,  0,  0,COM,COM,WAL,  0,  0,COM,WAL,  0,WAL,
	WAL,  0,COM,COM,WAL,  0,COM,COM,WAL,  0,  0,COM,COM,WAL,  0,  0,COM,WAL,  0,WAL,
	WAL,  0,COM,COM,WAL,  0,COM,COM,WAL,  0,  0,COM,COM,WAL,COM,WAL,  0,  0,  0,WAL,
	WAL,  0,COM,COM,COM,COM,COM,WAL,  0,  0,  0,COM,COM,COM,COM,WAL,  0,  0,  0,WAL,
	WAL,  0,COM,COM,WAL,  0,  0,  0,  0,  0,  0,COM,COM,WAL,COM,WAL,  0,  0,  0,WAL,
	WAL,  0,COM,COM,WAL,  0,  0,  0,  0,  0,  0,COM,COM,WAL,  0,  0,  0,  0,  0,WAL,
	WAL,  0,COM,COM,WAL,  0,  0,  0,  0,  0,  0,COM,COM,WAL,  0,  0,  0,  0,  0,WAL,
	WAL,COM,COM,COM,WAL,WAL,  0,  0,  0,  0,COM,COM,COM,WAL,WAL,  0,  0,  0,  0,GAT,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 40
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,TRE,TRE,TRE,TRE,TRE,TRE,APL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,TRE,TRE,LEM,TRE,TRE,TRE,APL,APL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,TRE,TRE,TRE,TRE,TRE,TRE,APL,APL,APL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,COW,COW,COW,COW,COW,COW,COW,APL,APL,APL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,LOC,COW,COW,COW,COW,COW,COW,COW,APL,APL,APL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,COW,COW,COW,COW,COW,COW,COW,APL,APL,APL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,COW,COW,COW,WAL,COW,COW,COW,APL,APL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,COW,COW,COW,COW,COW,COW,COW,APL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,COW,COW,COW,COW,COW,COW,COW,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 41
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,  0,  0,WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,
	WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,  0,  0,WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,
	WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,  0,  0,WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,
	WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,GIR,  0,WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,
	WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,  0,ELE,WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,
	WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,  0,  0,WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,
	WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,  0,  0,WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,
	WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,  0,  0,WAL,POL,WAL,POL,WAL,POL,WAL,POL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,LOC,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 42
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,ICE,ICE,WAL,WAL,WAL,WAL,WAL,WAL,CAK,GAT,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,ICE,ICE,ICE,ICE,WAL,WAL,WAL,WAL,WAL,ICE,ICE,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,  0,ICE,ICE,ICE,ICE,  0,WAL,WAL,WAL,WAL,ICE,ICE,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,ICE,ICE,WAL,WAL,WAL,WAL,WAL,WAL,ICE,ICE,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,COW,ICE,ICE,GIR,GIR,GIR,GIR,GIR,GIR,ICE,ICE,COW,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,COW,ICE,ICE,ELE,ELE,ELE,ELE,ELE,ELE,ICE,ICE,COW,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,ICE,ICE,WAL,WAL,WAL,WAL,WAL,WAL,ICE,ICE,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,ICE,ICE,WAL,WAL,WAL,WAL,  0,ICE,ICE,ICE,ICE,  0,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,ICE,ICE,WAL,WAL,WAL,WAL,WAL,ICE,ICE,ICE,ICE,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,CAK,LOC,WAL,WAL,WAL,WAL,WAL,WAL,ICE,ICE,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 43
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,CLK,  0,  0,  0,POL,WAL,CHE,  0,  0,  0,APL,  0,  0,  0,  0,WAL,
	WAL,  0,  0,WAL,WAL,CLK,  0,WAL,POL,WAL,CHE,WAL,  0,APL,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,WAL,WAL,WAL,CLK,  0,POL,WAL,CHE,  0,APL,WAL,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,WAL,WAL,WAL,WAL,CLK,POL,WAL,CHE,APL,WAL,WAL,WAL,WAL,  0,  0,  0,WAL,
	WAL,LOC,TRE,TRE,LEM,TRE,TRE,TRE,  0,GAT,  0,TRE,TRE,TRE,LEM,TRE,TRE,TRE,  0,WAL,
	WAL,  0,  0,WAL,WAL,WAL,WAL,APL,CHE,WAL,POL,CLK,WAL,WAL,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,WAL,WAL,WAL,APL,  0,CHE,WAL,POL,  0,CLK,WAL,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,WAL,WAL,APL,  0,WAL,CHE,WAL,POL,WAL,  0,CLK,WAL,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,WAL,APL,  0,WAL,WAL,CHE,WAL,POL,WAL,WAL,  0,CLK,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,APL,  0,  0,  0,  0,CHE,  0,POL,  0,  0,  0,  0,CLK,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 44
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,  0,TRE,TRE,  0,WAL,WAL,WAL,WAL,WAL,  0,TRE,TRE,  0,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,TRE,WAL,WAL,TRE,WAL,WAL,TRE,TRE,  0,TRE,WAL,WAL,TRE,  0,LEM,TRE,  0,WAL,
	WAL,TRE,WAL,WAL,WAL,  0,TRE,TRE,  0,  0,TRE,  0,WAL,WAL,  0,TRE,  0,  0,TRE,WAL,
	WAL,TRE,WAL,  0,TRE,LEM,TRE,WAL,  0,TRE,WAL,TRE,WAL,  0,TRE,WAL,TRE,WAL,  0,GAT,
	WAL,LOC,WAL,TRE,WAL,WAL,TRE,WAL,TRE,WAL,WAL,TRE,WAL,TRE,WAL,WAL,TRE,WAL,WAL,WAL,
	WAL,WAL,WAL,TRE,WAL,WAL,TRE,WAL,TRE,WAL,WAL,TRE,WAL,TRE,WAL,WAL,TRE,WAL,WAL,WAL,
	WAL,WAL,WAL,TRE,WAL,TRE,  0,WAL,TRE,WAL,WAL,TRE,WAL,TRE,WAL,WAL,TRE,WAL,WAL,WAL,
	WAL,WAL,WAL,  0,TRE,  0,WAL,WAL,TRE,WAL,TRE,  0,WAL,TRE,WAL,TRE,  0,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,TRE,  0,WAL,WAL,  0,TRE,  0,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 45
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,ICE,ICE,  0,LOC,  0,  0,CAK,CAK,  0,  0,  0,  0,CHE,CHE,  0,  0,  0,WAL,
	WAL,ICE,WAL,WAL,ICE,  0,  0,CAK,WAL,WAL,CAK,  0,  0,CHE,WAL,WAL,CHE,  0,  0,WAL,
	WAL,ICE,WAL,WAL,ICE,  0,  0,CAK,WAL,WAL,CAK,  0,  0,CHE,WAL,WAL,CHE,  0,  0,WAL,
	GAT,  0,ICE,ICE,  0,  0,  0,  0,CAK,CAK,  0,  0,  0,  0,CHE,CHE,  0,  0,  0,WAL,
	WAL,WAL,TRE,TRE,WAL,WAL,WAL,WAL,TRE,TRE,WAL,WAL,WAL,WAL,TRE,TRE,WAL,WAL,WAL,WAL,
	WAL,WAL,TRE,TRE,WAL,WAL,WAL,WAL,TRE,TRE,WAL,WAL,WAL,WAL,TRE,TRE,WAL,WAL,WAL,WAL,
	WAL,  0,ICE,ICE,  0,  0,  0,  0,CAK,CAK,  0,  0,  0,  0,APL,APL,  0,  0,  0,WAL,
	WAL,ICE,WAL,WAL,ICE,  0,  0,CAK,WAL,WAL,CAK,  0,  0,APL,WAL,WAL,APL,  0,  0,WAL,
	WAL,ICE,WAL,WAL,ICE,  0,  0,CAK,WAL,WAL,CAK,  0,  0,APL,WAL,WAL,APL,  0,  0,WAL,
	WAL,  0,ICE,ICE,  0,  0,  0,  0,CAK,CAK,  0,  0,  0,  0,WAL,WAL,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 46
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,LOC,  0,ELE,  0,WAL,COW,COW,WAL,  0,GIR,  0,GIR,  0,GIR,  0,WAL,  0,  0,WAL,
	WAL,  0,ELE,  0,ELE,WAL,COW,GIR,WAL,  0,  0,ELE,  0,ELE,  0,  0,WAL,TRE,POL,WAL,
	WAL,  0,  0,LEM,  0,WAL,COW,COW,  0,  0,  0,  0,COW,  0,  0,  0,  0,  0,  0,WAL,
	WAL,ELE,  0,  0,  0,WAL,ELE,COW,COW,  0,GIR,  0,  0,  0,GIR,  0,WAL,WAL,WAL,WAL,
	WAL,  0,ELE,  0,  0,WAL,WAL,WAL,WAL,  0,  0,ELE,  0,ELE,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,  0,ELE,  0,ELE,  0,ELE,  0,WAL,WAL,WAL,WAL,ELE,  0,  0,  0,WAL,
	WAL,  0,TRE,  0,  0,  0,ELE,  0,ELE,  0,  0,GIR,GIR,GIR,WAL,ELE,ELE,  0,  0,WAL,
	WAL,POL,POL,WAL,ELE,  0,  0,LEM,  0,  0,  0,  0,GIR,GIR,WAL,ELE,ELE,ELE,  0,WAL,
	GAT,TRE,TRE,WAL,  0,ELE,  0,  0,ELE,  0,  0,WAL,GIR,GIR,WAL,ELE,LEM,ELE,ELE,WAL,
	WAL,POL,POL,WAL,ELE,  0,ELE,  0,  0,  0,GIR,WAL,GIR,GIR,WAL,ELE,ELE,ELE,ELE,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 47
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,GLA,  0,  0,  0,  0,  0,  0,  0,GLA,  0,  0,  0,  0,  0,WAL,
	WAL,  0,WAL,WAL,WAL,GLA,WAL,CAR,WAL,AIR,WAL,CAR,WAL,GLA,WAL,WAL,WAL,WAL,  0,WAL,
	WAL,  0,CAR,CAR,CAR,GLA,WAL,CAR,WAL,AIR,WAL,CAR,WAL,GLA,CAR,CAR,CAR,CAR,  0,WAL,
	WAL,  0,WAL,WAL,WAL,GLA,WAL,CAR,WAL,AIR,WAL,CAR,WAL,GLA,WAL,WAL,WAL,WAL,  0,WAL,
	WAL,  0,CAR,CAR,CAR,GLA,WAL,CAR,WAL,AIR,WAL,CAR,WAL,GLA,CAR,CAR,CAR,CAR,  0,WAL,
	WAL,LOC,WAL,WAL,WAL,GLA,WAL,CAR,WAL,AIR,WAL,CAR,WAL,GLA,WAL,WAL,WAL,WAL,  0,WAL,
	WAL,  0,CAR,CAR,CAR,GLA,WAL,CAR,WAL,AIR,WAL,CAR,WAL,GLA,CAR,CAR,CAR,CAR,  0,WAL,
	WAL,  0,WAL,WAL,WAL,GLA,WAL,CAR,WAL,AIR,WAL,CAR,WAL,GLA,WAL,WAL,WAL,WAL,  0,WAL,
	WAL,  0,CAR,CAR,CAR,GLA,WAL,CAR,WAL,AIR,WAL,CAR,WAL,GLA,CAR,CAR,CAR,CAR,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,GAT,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 48
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,  0,  0,  0,  0,WAL,
	WAL,  0,CHE,WAL,APL,  0,WAL,GIR,GIR,GIR,GIR,GIR,GIR,WAL,  0,APL,WAL,CHE,  0,WAL,
	WAL,  0,CHE,WAL,APL,  0,WAL,TRE,WAL,COW,COW,WAL,TRE,WAL,  0,APL,WAL,CHE,  0,WAL,
	WAL,  0,CHE,WAL,APL,  0,WAL,ELE,ELE,WAL,WAL,ELE,ELE,WAL,  0,APL,WAL,CHE,  0,WAL,
	WAL,LOC,WAL,WAL,WAL,  0,ICE,ELE,LEM,POL,POL,LEM,ELE,ICE,  0,WAL,WAL,WAL,  0,GAT,
	WAL,  0,APL,WAL,CHE,  0,WAL,ELE,ELE,WAL,WAL,ELE,ELE,WAL,  0,CHE,WAL,APL,  0,WAL,
	WAL,  0,APL,WAL,CHE,  0,WAL,TRE,WAL,COW,COW,WAL,TRE,WAL,  0,CHE,WAL,APL,  0,WAL,
	WAL,  0,APL,WAL,CHE,  0,WAL,GIR,GIR,GIR,GIR,GIR,GIR,WAL,  0,CHE,WAL,APL,  0,WAL,
	WAL,  0,  0,  0,  0,  0,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,  0,  0,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 49
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,LOC,  0,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,  0,WAL,TRE,WAL,WAL,TRE,TRE,WAL,TRE,TRE,WAL,TRE,TRE,WAL,WAL,TRE,WAL,  0,WAL,
	WAL,  0,WAL,TRE,  0,WAL,WAL,TRE,WAL,TRE,TRE,WAL,TRE,WAL,WAL,  0,TRE,WAL,  0,WAL,
	WAL,  0,WAL,AIR,TRE,  0,WAL,TRE,TRE,WAL,WAL,TRE,TRE,WAL,  0,TRE,AIR,WAL,  0,WAL,
	WAL,  0,  0,WAL,AIR,TRE,  0,TRE,LEM,WAL,WAL,LEM,TRE,  0,TRE,AIR,WAL,  0,  0,WAL,
	WAL,  0,  0,  0,WAL,AIR,TRE,  0,WAL,TRE,TRE,WAL,  0,TRE,AIR,WAL,  0,  0,  0,WAL,
	WAL,  0,  0,  0,  0,WAL,AIR,TRE,WAL,TRE,TRE,WAL,TRE,AIR,WAL,  0,  0,  0,  0,WAL,
	WAL,  0,COW,  0,  0,  0,WAL,CAR,CAR,CAR,CAR,CAR,CAR,WAL,  0,  0,  0,COW,  0,WAL,
	WAL,  0,  0,COW,  0,  0,  0,WAL,WAL,WAL,WAL,WAL,WAL,  0,  0,  0,COW,  0,  0,WAL,
	WAL,  0,  0,  0,  0,  0,  0,  0,  0,GAT,WAL,  0,  0,  0,  0,  0,  0,  0,  0,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,

// 50
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
	WAL,CRY,CRO,TRE,APL,COW,CHE,POL,GIR,ICE,CAK,COM,CAR,BAL,CLK,ELE,GLA,MON,AIR,WAL,
	WAL,CRY,CRO,TRE,APL,WAL,WAL,WAL,WAL,ICE,CAK,WAL,WAL,WAL,WAL,ELE,GLA,MON,AIR,WAL,
	WAL,CRY,CRO,TRE,APL,WAL,CHE,POL,GIR,ICE,CAK,WAL,  0,  0,WAL,ELE,GLA,MON,AIR,WAL,
	GAT,CRY,CRO,TRE,APL,WAL,CHE,POL,GIR,ICE,CAK,WAL,  0,  0,WAL,ELE,GLA,MON,AIR,WAL,
	WAL,LOC,CRO,TRE,APL,WAL,WAL,WAL,WAL,ICE,CAK,WAL,  0,  0,WAL,ELE,GLA,MON,AIR,WAL,
	WAL,CRY,CRO,TRE,APL,COW,CHE,POL,WAL,ICE,CAK,WAL,  0,  0,WAL,ELE,GLA,MON,AIR,WAL,
	WAL,CRY,CRO,TRE,APL,COW,CHE,POL,WAL,ICE,CAK,WAL,  0,  0,WAL,ELE,GLA,MON,AIR,WAL,
	WAL,CRY,CRO,TRE,APL,WAL,CHE,POL,WAL,ICE,CAK,WAL,  0,  0,WAL,ELE,GLA,MON,AIR,WAL,
	WAL,CRY,CRO,TRE,APL,WAL,WAL,WAL,WAL,ICE,CAK,WAL,WAL,WAL,WAL,ELE,GLA,MON,AIR,WAL,
	WAL,CRY,CRO,TRE,APL,COW,CHE,POL,GIR,ICE,CAK,COM,CAR,BAL,CLK,ELE,GLA,MON,AIR,WAL,
	WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,WAL,
};

// level paswords
const char LevelPsw[(LEVNUM+1)*PSWLEN+1] =
	"INTRO"		// 0 
	"GOLEM"		// 1 
	"KRONE"		// 2 
	"MYDLO"		// 3 
	"LEDEN"		// 4 
	"STROP"		// 5 
	"LILIE"		// 6 
	"RYBKA"		// 7 
	"KLAUN"		// 8 
	"BRAUN"		// 9 
	"WHITE"		// 10
	"MOUSE"		// 11
	"DREAM"		// 12
	"IDEAL"		// 13
	"ILUZE"		// 14
	"SAINT"		// 15
	"BELLS"		// 16
	"TROJA"		// 17
	"EMOCE"		// 18
	"BASTL"		// 19
	"ISLAM"		// 20
	"JEANS"		// 21
	"METAL"		// 22
	"MIKRO"		// 23
	"SENZA"		// 24
	"GALAX"		// 25
	"STONE"		// 26
	"SLAVE"		// 27
	"FORTE"		// 28
	"LUCIE"		// 29
	"NATUR"		// 30
	"BIENE"		// 31
	"KATZE"		// 32
	"HYDRO"		// 33
	"FAUNA"		// 34
	"ULTRA"		// 35
	"TODAY"		// 36
	"HOROR"		// 37
	"GAPPA"		// 38
	"RETAL"		// 39
	"CLOCK"		// 40
	"HOMER"		// 41
	"BUNNY"		// 42
	"FOTON"		// 43
	"QUACK"		// 44
	"HAFIK"		// 45
	"DIZZY"		// 46
	"STARK"		// 47
	"ZARAZ"		// 48
	"DUKEN"		// 49
	"STORY";	// 50

// Level solution
const char* Solution[LEVNUM+1] = {
	// 0: RRRRRRRRRRRRRRRRRRRULLLLLLLLLLLLLLLLLLLDDRRRRRRRRR
	"RRRRRRRRRRRRRRRRRRRULLLLLLLLLLLLLLLLLLLDDRRRRRRRRR",

	// 1: RRRR RRRR RRRR RRUU ULLL LLLL LLLL DDDD DDRR RRRR RDRR RRRR RR
	"RRRRRRRRRRRRRRUUULLLLLLLLLLLDDDD"
	"DDRRRRRRRDRRRRRRRR",

	// 2: UURR RRRR RRRU LLLL LLUR RRRR RULL LLLL URRR RRRR DDDD DDLL LLDD
	"UURRRRRRRRRULLLLLLURRRRRRULLLLLL"
	"URRRRRRRDDDDDDLLLLDD",

	// 3: UUUL URRU LLUR RULU RRRR RRRR RRRR RDDD DDDL UUUU LDDD DLUU UULD DDLL L
	"UUULURRULLURRULURRRRRRRRRRRRRDDD"
	"DDDLUUUULDDDDLUUUULDDDLLL",

	// 4: RRRDDDDDRRRRRRRRRRULLLLURRULLLLDDLLLURRUURRRULLLLLLLLLUUUURRRRRRRDRRRRRRRRULLLLLLLU
	"RRRDDDDDRRRRRRRRRRULLLLURRULLLLD"
	"DLLLURRUURRRULLLLLLLLLUUUURRRRRR"
	"RDRRRRRRRRULLLLLLLU",

	// 5: RRDDDRRRRULLLURRRULLLLURRRRULLLLLURRRRRRRRRRRRRRRDLDDDDDLUUUULDDDDLUUUULDDDDDDLLLLLLLLLLLUUL
	"RRDDDRRRRULLLURRRULLLLURRRRULLLL"
	"LURRRRRRRRRRRRRRRDLDDDDDLUUUULDD"
	"DDLUUUULDDDDDDLLLLLLLLLLLUUL",

	// 6: RRRRRDDDRRRRRULLLLURRRRULLLLURRRRULLLLURRRURRRRRDDDDDDDDDLLLLLLLLLLLLLLL
	"RRRRRDDDRRRRRULLLLURRRRULLLLURRR"
	"RULLLLURRRURRRRRDDDDDDDDDLLLLLLL"
	"LLLLLLLL",

	// 7: RRRRDDLLDDRRRRRULURRRRDLDRRRRRRRUULLLULLLLLLLURRRRRRRRRRUULLLLLLDLULDLULDLULLUURRRRRU
	"RRRRDDLLDDRRRRRULURRRRDLDRRRRRRR"
	"UULLLULLLLLLLURRRRRRRRRRUULLLLLL"
	"DLULDLULDLULLUURRRRRU",

	// 8: DDDDRRUUUUUUUURRRRRRDDDLLDDDDRRRRULLLURRRULLURULUURRRRRRDDDDDDDDDLLLLLL
	"DDDDRRUUUUUUUURRRRRRDDDLLDDDDRRR"
	"RULLLURRRULLURULUURRRRRRDDDDDDDD"
	"DLLLLLL",

	// 9: UUUUURDDDDDRRRRUURRRULLLURRRULLLURRRRUUULLLLLLLLDLULLLLLLLLDDDDRRRRDLLLDRRRDLLDDRRRRRRD
	"UUUUURDDDDDRRRRUURRRULLLURRRULLL"
	"URRRRUUULLLLLLLLDLULLLLLLLLDDDDR"
	"RRRDLLLDRRRDLLDDRRRRRRD",

	// 1: DDDDDRRUUUUUUUUURRRRRRRRDLLLDRDLLLDDDDDDRRRRRRRRRURULURULURULURULULLLDDDDDDDDDLLLUUUUU
	"DDDDDRRUUUUUUUUURRRRRRRRDLLLDRDL"
	"LLDDDDDDRRRRRRRRRURULURULURULURU"
	"LULLLDDDDDDDDDLLLUUUUU",

	// 11: RRDDDLDRDRRRUUUUULLULURURRURRDRRRURRRRDDRDLDRDDDRDLDLLLUUUUULULLLDDRRDLLDRRDLLLUUUUL
	"RRDDDLDRDRRRUUUUULLULURURRURRDRR"
	"RURRRRDDRDLDRDDDRDLDLLLUUUUULULL"
	"LDDRRDLLDRRDLLLUUUUL",

	// 12: DDDDDRRUUUUURRRRRRDDDLLLLDDRURDRURDRURDRURDRUULLLLLUULLLLLLDDDLUUUUUUURRRRRRRRRRRRRRRDDDLLDRRDDDRUUUUUUUULLLLLLLLLU
	"DDDDDRRUUUUURRRRRRDDDLLLLDDRURDR"
	"URDRURDRURDRUULLLLLUULLLLLLDDDLU"
	"UUUUUURRRRRRRRRRRRRRRDDDLLDRRDDD"
	"RUUUUUUUULLLLLLLLLU",

	// 13: RRUULUURDRDDDLLLDDDDDRURURRURRURRURRULLLUURRDRRDRUUURRRRRDLLLDDDRRRDDLLDDRRDLLLLUUULLLDRRDDLULLULDDLULDD
	"RRUULUURDRDDDLLLDDDDDRURURRURRUR"
	"RURRULLLUURRDRRDRUUURRRRRDLLLDDD"
	"RRRDDLLDDRRDLLLLUUULLLDRRDDLULLU"
	"LDDLULDD",

	// 14: UUUURRDLDDDRRRUUUURRDDDDRRRULULURURRRDDRRRRRRDDDDLDRDDLLUUULLDDDLUUULDDDLLLUURULLLLLLLLLUUL
	"UUUURRDLDDDRRRUUUURRDDDDRRRULULU"
	"RURRRDDRRRRRRDDDDLDRDDLLUUULLDDD"
	"LUUULDDDLLLUURULLLLLLLLLUUL",

	// 15: RRUUUURRRRRRDDRDRDDDLDLLUURULULLLURRRRRRRRRDLLLDDDRRRDLLLLLLLLLURRRURULULLLURRRRUULLLLLLDDDDR
	"RRUUUURRRRRRDDRDRDDDLDLLUURULULL"
	"LURRRRRRRRRDLLLDDDRRRDLLLLLLLLLU"
	"RRRURULULLLURRRRUULLLLLLDDDDR",

	// 16: UUUUURRRDRDRDRDRRURURURURRDDDDDDLLLLLDRDDLLLLUURULLLLLUUUUUURRRRDRRRRDLLLDRDD
	"UUUUURRRDRDRDRDRRURURURURRDDDDDD"
	"LLLLLDRDDLLLLUURULLLLLUUUUUURRRR"
	"DRRRRDLLLDRDD",

	// 17: DDDDRURDRUUULLUULUUUURDDDRDRUUULURRRRRRDDLLLDDRRRRRUURRDDDLDLDLLULLLDDDRURDRRRRUURDDD
	"DDDDRURDRUUULLUULUUUURDDDRDRUUUL"
	"URRRRRRDDLLLDDRRRRRUURRDDDLDLDLL"
	"ULLLDDDRURDRRRRUURDDD",

	// 18: DDDDRRRUUUURRRRDRDDDLLLURDRRRRRUULDDLLUUURUUULUUULLLDDRUURRDDDDLLLLLLUUULDDDDDDDRUUURRRRRRRRRRRDDDDRRRUUUUUUUULDDDDDDLUUUULDLLLLLUUUURRDRUR
	"DDDDRRRUUUURRRRDRDDDLLLURDRRRRRU"
	"ULDDLLUUURUUULUUULLLDDRUURRDDDDL"
	"LLLLLUUULDDDDDDDRUUURRRRRRRRRRRD"
	"DDDRRRUUUUUUUULDDDDDDLUUUULDLLLL"
	"LUUUURRDRUR",

	// 19: DDDDDRUUUUURDDDDDRUUUUURDDDDDRUUUUURDDDDDRRRRRRRRRRRULLLLLLLLLLURRRRRRRRRRULLLLLLLLLLURRRRRRRRRRULLLLLLLLLURRRRRRRRRULLLLLLLLLURRRRRRRRRULLLLLLLLL
	"DDDDDRUUUUURDDDDDRUUUUURDDDDDRUU"
	"UUURDDDDDRRRRRRRRRRRULLLLLLLLLLU"
	"RRRRRRRRRRULLLLLLLLLLURRRRRRRRRR"
	"ULLLLLLLLLURRRRRRRRRULLLLLLLLLUR"
	"RRRRRRRRULLLLLLLLLLLLLLLLLDRRRRR"
	"RRDLLLLLLLDRRRRRRRD",

	// 2: RRRRRRDRRRURURRRDRDLLULDLDRRRRRDLLLLLLULLULULULDLLDDDDRRRDLLLLLUUUUUUUURRRRRRRRRRRRRRRRRDDDDDDDDLUU
	"RRRRRRDRRRURURRRDRDLLULDLDRRRRRD"
	"LLLLLLULLULULULDLLDDDDRRRDLLLLLU"
	"UUUUUUURRRRRRRRRRRRRRRRRDDDDDDDD"
	"LUU",

	// 21: LDDRDDLLULULULULULLDDDDDRRULULUURRDRDRDRDRRRUUULLULULULULLLUURDRURDRDRDRDRDRRRURURURURURRRDDLULDLDLDLDLDLLDDDRRRURURURURRDDLDDRR
	"LDDRDDLLULULULULULLDDDDDRRULULUU"
	"RRDRDRDRDRRRUUULLULULULULLLUURDR"
	"URDRDRDRDRDRRRURURURURURRRDDLULD"
	"LDLDLDLDLLDDDRRRURURURURRDDLDDRR",

	// 22: DDDDDDRRRRUUURRDDDDDRRRUURUULLDRDDDRRRUUUUUUURDDRDDDDRDDRRULURULLURRULLURRULLLURRRULLLLLLLDRDRDDDDDDDLLLLLLUUUUUUURRUULDLULLLLLDRRRRDLLLLDRRDLLDRRRDDLLLLDRRRDLLLL
	"DDDDDDRRRRUUURRDDDDDRRRUURUULLDR"
	"DDDRRRUUUUUUURDDRDDDDRDDRRULURUL"
	"LURRULLURRULLLURRRULLLLLLLDRDRDD"
	"DDDDDLLLLLLUUUUUUURRUULDLULLLLLD"
	"RRRRDLLLLDRRDLLDRRRDDLLLLDRRRDLL"
	"LL",

	// 23: DDDDDRRRRRRRUUULLLUURRDRRRDDLDDRRRUUUUUULULULULLLLLDLDLDDDDDDDRRRRRRUUULLLUURDRRRRDLDDDRRRRRUUULUUUULULURRRDDDDDRRRRDLLLDRRRDLLDRRR
	"DDDDDRRRRRRRUUULLLUURRDRRRDDLDDR"
	"RRUUUUUULULULULLLLLDLDLDDDDDDDRR"
	"RRRRUUULLLUURDRRRRDLDDDRRRRRUUUL"
	"UUUULULURRRDDDDDRRRRDLLLDRRRDLLD"
	"RRR",

	// 24: DDLLULUULLLLLUURRRUUULLDRRDDLLLDDRRRRRDDRDRRRRURUURRRRRRUULLLLUUURRRRDLLLLDDRRRRDDLLLLLLDDLDLLLLULUULLLLLDDDDRRRUULDLULUURRRRRDDRDRRRRURUURRRRRRDDDDLLLLUURDRURRUULLLLLLDDLDLLUUURUUUUULLDRDLDRDLDRDDLLLDDRRURRURRDDLLLD
	"DDLLULUULLLLLUURRRUUULLDRRDDLLLD"
	"DRRRRRDDRDRRRRURUURRRRRRUULLLLUU"
	"URRRRDLLLLDDRRRRDDLLLLLLDDLDLLLL"
	"ULUULLLLLDDDDRRRUULDLULUURRRRRDD"
	"RDRRRRURUURRRRRRDDDDLLLLUURDRURR"
	"UULLLLLLDDLDLLUUURUUUUULLDRDLDRD"
	"LDRDDLLLDDRRURRURRDDLLLD",

	// 25: RRRRRRRRRRRRRRRRRDLDDDDDDDDLUUUUUUULULLLLLLLLLLLLLDDDDDDDDRUUUUUUURRDDDDDDDRUUUUUUURRRRRRRRDDDDDDDLUUUUUULLDDDDDDLUUUUUULLDDDDDDD
	"RRRRRRRRRRRRRRRRRDLDDDDDDDDLUUUU"
	"UUULULLLLLLLLLLLLLDDDDDDDDRUUUUU"
	"UURRDDDDDDDRUUUUUUURRRRRRRRDDDDD"
	"DDLUUUUUULLDDDDDDLUUUUUULLDDDDDD"
	"D",

	// 26: LURURURURURURURURRRDRDRDRDRDRDRDRUUUUULULULULLLLLLLLLDDLLULLDRDLDRRURRRURURRRRRDRDRDRDRDDDRDL
	"LURURURURURURURURRRDRDRDRDRDRDRD"
	"RUUUUULULULULLLLLLLLLDDLLULLDRDL"
	"DRRURRRURURRRRRDRDRDRDRDDDRDL",

	// 27: RDRDDLLDDRRRDDDDLLLUURRRUULLLUURRRRUUURRDDDDDLDDRRDRDLLUULUURUUURRURURRRRRRDDDDDRDLDLDLUUUULLDDDLUULLU
	"RDRDDLLDDRRRDDDDLLLUURRRUULLLUUR"
	"RRRUUURRDDDDDLDDRRDRDLLUULUURUUU"
	"RRURURRRRRRDDDDDRDLDLDLUUUULLDDD"
	"LUULLU",

	// 28: UUUURRRRRRRDRRRDDDRRDDRDRURULLURRULULDLDLLDLULDLLLDLDLULURRULLURURDRDRRUUUUR
	"UUUURRRRRRRDRRRDDDRRDDRDRURULLUR"
	"RULULDLDLLDLULDLLLDLDLULURRULLUR"
	"URDRDRRUUUUR",

	// 29: DRRUUULDRDDLLLLLDDDDDLUURUU UUUUURRDDLLDD LLLLUUUULLDD RRDDDDDLLDDRRRULUUUURRRRRRRRRRRRRUULUURRRDDLULDDDD DDRRDDLULDLUURUURRULLLDLLLLLLLLLLLLLLURRRRRRRRRRRDDDDLLUU
	"DRRUUULDRDDLLLLLDDDDDLUURUUUUUUU"
	"RRDDLLDDLLLLUUUULLDDRRDDDDDLLDDR"
	"RRULUUUURRRRRRRRRRRRRUULUURRRDDL"
	"ULDDDDDDRRDDLULDLUURUURRULLLDLLL"
	"LLLLLLLLLLLURRRRRRRRRRRDDDDLLUU",

	// 3: RRRRRRUULULULUUURRDRDRDDDDD RRRUUUUURURURRDDDLDLDLDDRRRRRUUUUUUUUULLLLLLLLLLLLLLLDDDDDDDDDRRRRRUULLLUUUUURRRRDDDDDDDRRRUUUUUUURRRRDDDDDLLLDDRRRRRRR
	"RRRRRRUULULULUUURRDRDRDDDDDRRRUU"
	"UUURURURRDDDLDLDLDDRRRRRUUUUUUUU"
	"ULLLLLLLLLLLLLLLDDDDDDDDDRRRRRUU"
	"LLLUUUUURRRRDDDDDDDRRRUUUUUUURRR"
	"RDDDDDLLLDDRRRRRRR",

	// 31: RRRRRRRRRRRRRRRRR DDDDLLLLLLLLLLLLLLLLL UUUUUURRRRRRRRRRRRRRRRRDDDDDDLLLLLLLLLLLLLLLLL UUUURRRRRRRRRRRRRRRRR UUUULLLLLLLLLLLLLLLLLDDDDDDRRRRRRRRRRRRRRRRR DDLLLLLLLLLD
	"RRRRRRRRRRRRRRRRRDDDDLLLLLLLLLLL"
	"LLLLLLUUUUUURRRRRRRRRRRRRRRRRDDD"
	"DDDLLLLLLLLLLLLLLLLLUUUURRRRRRRR"
	"RRRRRRRRRUUUULLLLLLLLLLLLLLLLLDD"
	"DDDDRRRRRRRRRRRRRRRRRDDLLLLLLLLL"
	"D",

	// 32: UUUURDLDDDDDDRDRDRRRULULULULUURURURURRRDLDLDLDDRDRDRDRDRRRULULULULUURURURURRRDLDLDLDDRDRDRDRDRRRULULULULUURURUURDRDDLDDRDR
	"UUUURDLDDDDDDRDRDRRRULULULULUURU"
	"RURURRRDLDLDLDDRDRDRDRDRRRULULUL"
	"ULUURURURURRRDLDLDLDDRDRDRDRDRRR"
	"ULULULULUURURUURDRDDLDDRDR",

	// 33: UUUURDDRDDRRUURUURRRRRDRDDDDDDDLDLLLLLUULUULLDDLDDLUUUUURRRRRRUUURURRRRRRRRRDDDDDLLLLDDDDLLLLLULUUULLLLDDLDDLUUURULURULUUURDDRDDRRRRUUURURRRRRDDDDDRRDRDRDDRUUUUR
	"UUUURDDRDDRRUURUURRRRRDRDDDDDDDL"
	"DLLLLLUULUULLDDLDDLUUUUURRRRRRUU"
	"URURRRRRRRRRDDDDDLLLLDDDDLLLLLUL"
	"UUULLLLDDLDDLUUURULURULUUURDDRDD"
	"RRRRUUURURRRRRDDDDDRRDRDRDDRUUUU"
	"R",

	// 34: LLLLDRDRDRDRDRURURURURURRRRDDDDDDDDDLLUUUUUUUUULLLLDLLLLLDRRRRDLLDDDLDLDLDRRURURURDRDRDLLULDLD
	"LLLLDRDRDRDRDRURURURURURRRRDDDDD"
	"DDDDLLUUUUUUUUULLLLDLLLLLDRRRRDL"
	"LDDDLDLDLDRRURURURDRDRDLLULDLD",

	// 35: DDDDRRRRRRDRRUURURURULULULLDLDLDRDRUURRDLDDDDLLLLLLLLUUUUUUUUURRRRRRRRRRRRRRRRRDDDDDDDDDLLLLLLLLLUULUUUUURU
	"DDDDRRRRRRDRRUURURURULULULLDLDLD"
	"RDRUURRDLDDDDLLLLLLLLUUUUUUUUURR"
	"RRRRRRRRRRRRRRRDDDDDDDDDLLLLLLLL"
	"LUULUUUUURU",

	// 36: DDDDDDDDDRRUUUUUUUUURRDDDDDDDDDRRUUUUUUUUURRDDDDDDDDDRRUUUUUUUUURRDDDDDDDDDRRUUUUUUUURRULLDDDDDDDDDLLUUUUUUUUULLDDDDDDDDDLLUUUUUUUUULLDDDDDDDDDLLUUUUUUUUULLDDDDDDDDDLLURRUUUUUUURRDDDDDDDRRUUUUUUURRDDDDDDDRRUUUUUUURRDDDDDDDRDD
	"DDDDDDDDDRRUUUUUUUUURRDDDDDDDDDR"
	"RUUUUUUUUURRDDDDDDDDDRRUUUUUUUUU"
	"RRDDDDDDDDDRRUUUUUUUURRULLDDDDDD"
	"DDDLLUUUUUUUUULLDDDDDDDDDLLUUUUU"
	"UUUULLDDDDDDDDDLLUUUUUUUUULLDDDD"
	"DDDDDLLURRUUUUUUURRDDDDDDDRRUUUU"
	"UUURRDDDDDDDRRUUUUUUURRDDDDDDDRD"
	"D",

	// 37: RRRRURUURRDDRRRUURRDDRDRRUUUURRDLDRDLDRDLDRDLDRDLLUUUUULLULUULLDDLLLUULLDDLDLLUUUULLDRDLDRDLDRDLDRDLDRRUUUUURRUUUURRRRRRRRRDDLULLLLDRDDLDLDRDLLLUULDDDRRRRRUUURDDDRURDRUULURURRRRR
	"RRRRURUURRDDRRRUURRDDRDRRUUUURRD"
	"LDRDLDRDLDRDLDRDLLUUUUULLULUULLD"
	"DLLLUULLDDLDLLUUUULLDRDLDRDLDRDL"
	"DRDLDRRUUUUURRUUUURRRRRRRRRDDLUL"
	"LLLDRDDLDLDRDLLLUULDDDRRRRRUUURD"
	"DDRURDRUULURURRRRR",

	// 38: UUUURRRRRRRRDDDLDDDDDDLURURULUUURRRDDDDDRDLLURUUURRDRDDDRRULULULULULULLLDLDLDLDDDLLURURURRRUUURRDDRDRRULULULUULLLDLDLDLDLDLDLUUUUURRUURRRRRRRDRURRRRRDDLULLLDRDRDRDRDRDRDR
	"UUUURRRRRRRRDDDLDDDDDDLURURULUUU"
	"RRRDDDDDRDLLURUUURRDRDDDRRULULUL"
	"ULULULLLDLDLDLDDDLLURURURRRUUURR"
	"DDRDRRULULULUULLLDLDLDLDLDLDLUUU"
	"UURRUURRRRRRRDRURRRRRDDLULLLDRDR"
	"DRDRDRDRDR",

	// 39: RRRRRDDDDDLLLDDDDLLURUUUURULURULLURRRDRRDRDDLDDDDDRUUURDDDRUUURDDDRRUUUURRUURRUULLLLLLULLLLLLLLLDDDDDDDDDRUUUUUUUURDDDDRRRDDDRRRRRUUUUUURDDDRRDDDRRDRRR
	"RRRRRDDDDDLLLDDDDLLURUUUURULURUL"
	"LURRRDRRDRDDLDDDDDRUUURDDDRUUURD"
	"DDRRUUUURRUURRUULLLLLLULLLLLLLLL"
	"DDDDDDDDDRUUUUUUUURDDDDRRRDDDRRR"
	"RRUUUUUURDDDRRDDDRRDRRR",

	// 4: RURURURURRRRRRDDDDDLDLDLLUR URURULURULLLLDLDLDLDLD RRURURURURDDLDLDDLLLLDRRRRRRD
	"RURURURURRRRRRDDDDDLDLDLLURURURU"
	"LURULLLLDLDLDLDLDRRURURURURDDLDL"
	"DDLLLLDRRRRRRD",

	// 41: RRUUUUUUUUULLLLLDDDDDDDDDRRRRRRRUUUUUUUUULLLLLLLLLDDDDDDDDDRRRRUUURDDDRRRRRRUUUUUUUUULLLLLLDDDDDLUUUUULLLLLLDDDDDDDDDRRRRRRUUURDDDRRRRRRRRUUUUUUUUULLLLLLLLDDDDDLUUUUULLLLLLLLDDDDDDDDDRRRRRRRRUUURDDDD
	"RRUUUUUUUUULLLLLDDDDDDDDDRRRRRRR"
	"UUUUUUUUULLLLLLLLLDDDDDDDDDRRRRU"
	"UURDDDRRRRRRUUUUUUUUULLLLLLDDDDD"
	"LUUUUULLLLLLDDDDDDDDDRRRRRRUUURD"
	"DDRRRRRRRRUUUUUUUUULLLLLLLLDDDDD"
	"LUUUUULLLLLLLLDDDDDDDDDRRRRRRRRU"
	"UURDDDD",

	// 42: LURULURULLURUULURURDRDLDDRDRURDRURDRURDDDLDRDRURULUURULULURULUR
	"LURULURULLURUULURURDRDLDDRDRURDR"
	"URDRURDDDLDRDRURULUURULULURULUR",

	// 43: DDDDDRRRURURURUUUULULULLLLDDDDDDDDDRRRRRRRRRRRRRRRRUUUUUUUUULLLLDLDLDDDDRDRDRDLLLLLLUUUUUUUUULLLLLLLDDDDRRRRRRDDLDLDLDRRRRRRUUUURURRRRRUUUULLLLLLDDDDL
	"DDDDDRRRURURURUUUULULULLLLDDDDDD"
	"DDDRRRRRRRRRRRRRRRRUUUUUUUUULLLL"
	"DLDLDDDDRDRDRDLLLLLLUUUUUUUUULLL"
	"LLLLDDDDRRRRRRDDLDLDLDRRRRRRUUUU"
	"RURRRRRUUUULLLLLLDDDDL",

	// 44: UUURURRRDDDLLDDDDRRURUUUURRURDDLDDDDDRRURUUUUULURURRRDRDLDLDDDDDRRURUUUUUURRDDR
	"UUURURRRDDDLLDDDDRRURUUUURRURDDL"
	"DDDDDRRURUUUUULURURRRDRDLDLDDDDD"
	"RRURUUUUUURRDDR",

	// 45: RRRRRRRRRRRRDDDLLDDDRRRDDDLLURULULLLDDDLLLLLLLLLLLLUUURUUURDDDRDDRRRUURUUURDDDRDDRRRUURUUURRUUULLLDDLLLUULLLDDLLLUULLLDDDL
	"RRRRRRRRRRRRDDDLLDDDRRRDDDLLURUL"
	"ULLLDDDLLLLLLLLLLLLUUURUUURDDDRD"
	"DRRRUURUUURDDDRDDRRRUURUUURRUUUL"
	"LLDDLLLUULLLDDLLLUULLLDDDL",

	// 46: DDRDRDRDDRDRDRDRRUUURUULUURRDRRURRRRRUULDDLLLLDLLULLDDRDDDDLDLLULULULUUUUUULLLDRRDLLDDRRRDDRDRDRDRRURUUUULUURRDRRURRDDRRRDDDDDLLLURRULLURRULLULLURUUULDDLUULDLULDDLLUULDDDRRRRRDLDDRRRDDDLUULLLUULLLLDRRRDLDRRRDLLLLLLURULULLLDRDDLUL
	"DDRDRDRDDRDRDRDRRUUURUULUURRDRRU"
	"RRRRRUULDDLLLLDLLULLDDRDDDDLDLLU"
	"LULULUUUUUULLLDRRDLLDDRRRDDRDRDR"
	"DRRURUUUULUURRDRRURRDDRRRDDDDDLL"
	"LURRULLURRULLULLURUUULDDLUULDLUL"
	"DDLLUULDDDRRRRRDLDDRRRDDDLUULLLU"
	"ULLLLDRRRDLDRRRDLLLLLLURULULLLDR"
	"DDLUL",

	// 47: DDDDRRRRRRRRUUUUUUUUULLDDDDDDDDDRRRRUUUUUUUUULLLLLLLLLLDDDDDDDDDRRRRRRRRRRRRUUUUUUUUULLLLLLLLLLLLDDDDDDDDDRRRRRRRRRRRRURDRURDRURUUUUUUUULLLLLLLLLLLLLDDDDDDDDDRRRRRRRRURDRURDRURUUUUUUUULLLLLLLLLLLLLLLLLDDDDDDDDDRRRRRRRRRRRRRRRRRULLLLLUURRRRRUULLLLLUURRRRRUULLLLLLLLLLLLLLLLLDDRRRRDDLLLLDDRRRRDDLLLLDRRRRRRRRD
	"DDDDRRRRRRRRUUUUUUUUULLDDDDDDDDD"
	"RRRRUUUUUUUUULLLLLLLLLLDDDDDDDDD"
	"RRRRRRRRRRRRUUUUUUUUULLLLLLLLLLL"
	"LDDDDDDDDDRRRRRRRRRRRRURDRURDRUR"
	"UUUUUUUULLLLLLLLLLLLLDDDDDDDDDRR"
	"RRRRRRURDRURDRURUUUUUUUULLLLLLLL"
	"LLLLLLLLLDDDDDDDDDRRRRRRRRRRRRRR"
	"RRRULLLLLUURRRRRUULLLLLUURRRRRUU"
	"LLLLLLLLLLLLLLLLLDDRRRRDDLLLLDDR"
	"RRRDDLLLLDRRRRRRRRD",

	// 48: UUUURRRRDDDDRRRRRRRRRURUUURRDDDRDDDDDLLLLUUUU LLDLULLLULDLLULUUULLDDDLDDRDDLDDRURDRRUULUURURRUUURRDRURRDDLDLLLDLDDRRURDRRUUURRDRDDDRRUUURUR
	"UUUURRRRDDDDRRRRRRRRRURUUURRDDDR"
	"DDDDDLLLLUUUULLDLULLLULDLLULUUUL"
	"LDDDLDDRDDLDDRURDRRUULUURURRUUUR"
	"RDRURRDDLDLLLDLDDRRURDRRUUURRDRD"
	"DDRRUUURUR",

	// 49: LLDDDDDDDRRUURDDRRUUUUUUURRRRRRDDDDDDDDDLLLLLURRRRULLURRUURUUUULLDDDLDLDLDLUULURUURULLLDDLUULLLDRDDRDLDDLULULULUUULLDDDDDDRDDRDRRRRRR
	"LLDDDDDDDRRUURDDRRUUUUUUURRRRRRD"
	"DDDDDDDDLLLLLURRRRULLURRUURUUUUL"
	"LDDDLDLDLDLUULURUURULLLDDLUULLLD"
	"RDDRDLDDLULULULUUULLDDDDDDRDDRDR"
	"RRRRR",

	// 5: RURRDLDRRRRDDLULLLLULDDDDRUURRDLDRRRRRRUUUUUULLLURRRURDDDDDDDDRRRRRRRRULLLURRRULLLURRRULLLURRRULLLURRRULLLLLLLLLLLLLLLLLDRRRDLLLDL
	"RURRDLDRRRRDDLULLLLULDDDDRUURRDL"
	"DRRRRRRUUUUUULLLURRRURDDDDDDDDRR"
	"RRRRRRULLLURRRULLLURRRULLLURRRUL"
	"LLURRRULLLLLLLLLLLLLLLLLDRRRDLLL"
	"DL",
};

